import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import "../styles/global.css";
import { Toaster } from "@/components/ui/toaster";
import LayoutProvider from "@/components/common/layout-provider";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto"
});

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Cộng đồng nước hoa",
  description: "Generated by create next app"
};

export default function RootLayout({
                                     children
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto.variable}`}>
    <body suppressHydrationWarning={true}>
    <Toaster />
    <LayoutProvider>{children}</LayoutProvider>
    </body>
    </html>
  );
}
